### ISSUE TITLE
Decrypt Fails

### ISSUE THREAD

**Issue by markieg9** [elliotwutingfeng/2fas-backup-decryptor#13]
Tried to decrypt the test/encrypted_test.2fas file with password example.com but it fails:

**ruby lib/decrypt.rb test/encrypted_test.2fas**
**Enter 2FAS encrypted backup password:**
**Failed to derive cipher key. Wrong password?**

Tried with my own 2FAS backup file but that also will not decrypt.

I am using ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]
on a Mac, Ventura 13.6

**Comment by elliotwutingfeng** [comment]
Thank you for the bug report. I am able to reproduce this on macOS Sonoma x86_64, ruby 2.6.10p210 (2022-04-12 revision 67958).

It looks like the Ruby interpreter bundled with macOS (which is meant for system use) uses a different encryption library (LibreSSL instead of OpenSSL) from most other implementations. I will investigate further on this.

In the meantime I suggest installing Ruby via homebrew as recommended here (https://www.ruby-lang.org/en/documentation/installation/#homebrew), and try running the program using that version of Ruby.

**Comment by markieg9** [comment]
Yes, Homebrew install of Ruby works fine.
